### ISSUE TITLE
Minimum Viable Repo checklist

### ISSUE THREAD

**Issue by eigenhombre** [eigenhombre/l1#33]
From https://gist.github.com/eigenhombre/204400c786f9dba3a8d3193d3ce1542a:

- [x] LICENSE file, including disclaimer
- [x] Automated build via Docker and GitHub Actions
- [x] Automated builds include unit tests
- [x] Automated builds include linting
- [x] Build badge
- [x] Artwork
- [ ] ~~Versioned~~ (see #34)
- [x] Minimum snippet / example
- [x] Link to API and/or `help` output
- [x] Project available in public package manager
- [x] Track outstanding TODOs in Issues
